# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "215e40ab3752da8d6b8af38fc779d816"
application_url = "https://horizon-kruger-soldier-atm.trycloudflare.com"
embedded = true
name = "boa-home-task-MN"
handle = "boa-home-task-mn"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-272.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://horizon-kruger-soldier-atm.trycloudflare.com/auth/callback",
  "https://horizon-kruger-soldier-atm.trycloudflare.com/auth/shopify/callback",
  "https://horizon-kruger-soldier-atm.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
